### ISSUE TITLE
Problem in Setting Up the extension

### ISSUE THREAD

**Issue by guptaaryan16** [EndBug/discuss-on-discord#21]
Hey @EndBug I am having problems sending and opening threads on my discord server through this extension. Can you help me I the same? You can the failed action on this link
https://github.com/guptaaryan16/My-portfolio/actions/runs/5053105392/jobs/9066622163
Thank you and this is a great project

**Comment by EndBug** [comment]
Looking at [this line](https://github.com/guptaaryan16/My-portfolio/actions/runs/5060970971/jobs/9084558322#step:5:231), it seems like your bot is not authorized to send messages on that channel 👀
